 ######################################################
#
# Main DBE configuration.
# Two Dallas temperature sensors calculate the difference between the incoming
# and outcoming water temperature. The aim is to have 20 degrees is a difference
# (But this will never be reached). The smaller the difference, the faster the fans go.
#
# There is a required sensor outside this config:
# sensor:
#  - platform: homeassistant
#    name: '${device_name} Heating Setting'
#    id: heating_setting
#    entity_id: sensor.living_room_heating
#
# This sensor indicates how 'open' the temperature valve is (I use Tado). When the valve
# is open (!= 0), the fans spin up. 120 seconds after the valve closes, all fans come to a full stop. 
# The boolean 'heating_off' is used to monitor this
#
####################################################################

###############################################################
# Clean DBE Configuration – Final Fixed Version
###############################################################

globals:
  - id: fanspeed
    type: float
    restore_value: no
    initial_value: '1'

  - id: heating_off
    type: bool
    initial_value: 'true'

  - id: mode_case        # <---- NEW: internal mode selector
    type: int
    restore_value: no
    initial_value: '0'

logger:
  level: DEBUG

one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

###############################################################
# SENSORS
###############################################################

sensor:
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

###############################################################
# SWITCH
###############################################################

switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true

###############################################################
# PWM + FAN
###############################################################

output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    id: fancontrol
    output: pwm_output
    name: "${device_name} Fan"
    speed_count: 100
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan Turned On!"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan Turned Off!"


###############################################################
# SCRIPTS
###############################################################

script:
  # --- 120-second non-blocking shutdown ---
  - id: shutdown_fans
    mode: restart
    then:
      - logger.log: "Heating closed → waiting 120 seconds..."
      - delay: 120s
      - fan.turn_off: fancontrol
      - globals.set:
          id: heating_off
          value: 'true'
      - logger.log: "Fans OFF after delay."

  # --- Main fan logic ---
  - id: control_fans
    mode: restart
    then:
      - lambda: |-
          float hs = id(heating_setting).state;
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;

          ESP_LOGD("fan_logic", "Heating Setting=%.2f  T1=%.2f  T2=%.2f", hs, t1, t2);

          // Case 0 → heating off
          if (hs < 1.0f) {
            id(mode_case) = 0;
            return;
          }

          // Case 1 → low power heating
          if (hs <= 10.0f) {
            id(mode_case) = 1;
            return;
          }

          // Case 2 → cooling mode
          float diff = fabs(t1 - t2);
          id(fanspeed) = fmaxf(0.0f, fminf(100.0f, (20.0f - diff) * 5.0f));
          id(mode_case) = 2;

      # CASE 0 — Heating off
      - if:
          condition:
            lambda: 'return id(mode_case) == 0;'
          then:
            - logger.log: "Heating OFF → starting shutdown timer"
            - script.execute: shutdown_fans

      # CASE 1 — Low heat (15% speed)
      - if:
          condition:
            lambda: 'return id(mode_case) == 1;'
          then:
            - logger.log: "Heating LOW → fixed 15% speed"
            - globals.set:
                id: heating_off
                value: 'false'
            - fan.turn_on:
                id: fancontrol
                speed: 15

      # CASE 2 — Cooling mode (dynamic speed)
      - if:
          condition:
            lambda: 'return id(mode_case) == 2;'
          then:
            - logger.log: !lambda "char msg[64]; sprintf(msg, \"Cooling mode → speed %.1f%%\", id(fanspeed)); return std::string(msg);"
            - globals.set:
                id: heating_off
                value: 'false'
            - fan.turn_on:
                id: fancontrol
                speed: !lambda 'return id(fanspeed);'
