 ######################################################
#
# Main DBE configuration.
# Two Dallas temperature sensors calculate the difference between the incoming
# and outgoing water temperature. The aim is to have 20 degrees is a difference
# (But this will never be reached). The smaller the difference, the faster the fans go.
#
# There is a required sensor outside this config:
# sensor:
#  - platform: homeassistant
#    name: "${device_name} Heating Setting"
#    id: heating_setting
#    entity_id: sensor.living_room_heating
#    on_value:
#      then:
#        - script.execute: control_fans
#
# This sensor indicates how 'open' the temperature valve is (I use Tado). When the valve
# is open (!= 0), the fans spin up. 120 seconds after the valve closes, all fans come to a full stop. 
# The boolean 'heating_off' is used to monitor this
#
# As this is a device-specific sensor, it's left out of this code
#
####################################################################
######################################################
# Optimized DBE Configuration
######################################################

globals:
  - id: fanspeed
    type: float
    restore_value: false
    initial_value: '0'

  - id: heating_off
    type: bool
    initial_value: 'true'

logger:
  level: DEBUG

one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

######################################################
# SENSORS
######################################################

sensor:
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

######################################################
# SWITCH
######################################################

switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true

######################################################
# PWM + FAN
######################################################

output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    id: fancontrol
    output: pwm_output
    name: "${device_name} Fan"
    speed_count: 100
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan Turned On!"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan Turned Off!"

######################################################
# SCRIPTS
######################################################

script:
  # --- 120-second shutdown ---
  - id: shutdown_fans
    mode: restart
    then:
      - logger.log: "Heating closed → waiting 120s..."
      - delay: 120s
      - fan.turn_off: fancontrol
      - globals.set:
          id: heating_off
          value: 'true'
      - logger.log: "Fans OFF after delay."

  # --- Main fan logic ---
  - id: control_fans
    mode: restart
    then:
      - lambda: |-
          // Read values
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;
          float deltaT = fabs(t1 - t2);

          // Decide fan speed
          float speed = 0;

          // Dynamic cooling mode → small ΔT → higher speed
          speed = fmaxf(0.0f, fminf(100.0f, (20.0f - deltaT) / 20.0f * 100.0f));
          if (speed < 10) speed = 10;  // Minimum airflow
          if (speed > 80) speed = 80;

          // Save fanspeed global
          id(fanspeed) = speed;

      - logger.log:
          format:  "ΔT=%.2f  Fanspeed=%.2f"
          args:
            - 'fabs(id(temp_1).state - id(temp_2).state)'
            - 'id(fanspeed)'

      - if:
          condition:
            lambda: 'return id(fanspeed) > 0;'
          then:
            - globals.set:
                id: heating_off
                value: 'false'
            - fan.turn_on:
                id: fancontrol
                speed: !lambda 'return id(fanspeed);'
          else:
            - fan.turn_off: fancontrol
            - globals.set:
                id: heating_off
                value: 'true'
