######################################################
# ESPHome: Interval-based fan control with HARD OFF
# - Exponential fan curve based on ΔT
# - Fan stops completely when ΔT < 1
# - Powerswitch cuts physical power when fan is off
# - Interval trigger every 5 seconds
######################################################

globals:
  - id: fanspeed
    type: float
    restore_value: false
    initial_value: '0'

  - id: heating_off
    type: bool
    initial_value: 'true'

logger:
  level: DEBUG

one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

######################################################
# Sensors
######################################################
sensor:
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

######################################################
# Powerswitch for physical fan control
######################################################
switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true

######################################################
# PWM output + fan
######################################################
output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    id: fancontrol
    internal: true
    output: pwm_output
    name: "${device_name} Fan"
    speed_count: 100
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan Turned On!"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan Turned Off!"

######################################################
# Interval trigger
######################################################
interval:
  - interval: 5s
    then:
      - script.execute: control_fans

######################################################
# Fan control script
######################################################
script:
  - id: control_fans
    mode: restart
    then:
      # --- 1️⃣ Calculate fanspeed ---
      - lambda: |-
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;

          // Safety: ignore invalid readings
          if (!isfinite(t1) || !isfinite(t2)) {
            id(fanspeed) = 0;
            return;
          }

          float deltaT = fabsf(t1 - t2);

          // HARD OFF zone
          if (deltaT < 1.0f) {
            id(fanspeed) = 0;
            return;
          }

          // Exponential fan curve
          const float dt_min = 2.0f;
          const float dt_max = 20.0f;
          const float speed_min = 10.0f;
          const float speed_max = 70.0f;
          const float exponent = 2.5f;

          float x = (deltaT - dt_min) / (dt_max - dt_min);
          x = fmaxf(0.0f, fminf(1.0f, x));

          float curve = 1.0f - powf(x, exponent);
          id(fanspeed) = speed_min + curve * (speed_max - speed_min);

      # --- 2️⃣ Apply fan state ---
      - if:
          condition:
            lambda: 'return id(fanspeed) > 0;'
          then:
            - fan.turn_on:
                id: fancontrol
                speed: !lambda 'return id(fanspeed);'
            - switch.turn_on: powerswitch
            - globals.set:
                id: heating_off
                value: 'false'
          else:
            - fan.turn_off: fancontrol
            - switch.turn_off: powerswitch
            - globals.set:
                id: heating_off
                value: 'true'

      # --- 3️⃣ Logging ---
      - logger.log:
          format: "ΔT=%.2f  Fanspeed=%.1f"
          args:
            - 'fabs(id(temp_1).state - id(temp_2).state)'
            - 'id(fanspeed)'
