######################################################
#
# Main DBE configuration.
# Two Dallas temperature sensors calculate the difference between the incoming
# and outcoming water temperature. The aim is to have 20 degrees is a difference
# (But this will never be reached). The smaller the difference, the faster the fans go.
#
# There is a required sensor outside this config:
# sensor:
#  - platform: homeassistant
#    name: '${device_name} Heating Setting'
#    id: heating_setting
#    entity_id: sensor.living_room_heating
#
# This sensor indicates how 'open' the temperature valve is (I use Tado). When the valve
# is open (!= 0), the fans spin up. 120 seconds after the valve closes, all fans come to a full stop. 
# The boolean 'heating_off' is used to monitor this
#
####################################################################

globals:
  - id: fanspeed
    type: float
    restore_value: no
    initial_value: '1'
  - id: heating_off
    type: bool
    initial_value: 'true'

logger:
  level: DEBUG

one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

###############################################################
# SENSORS
###############################################################

sensor:
  # Dallas 1
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  # Dallas 2
  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  # Fan Speed Counter
  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

###############################################################
# POWER SWITCH
###############################################################

switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true

###############################################################
# PWM OUTPUT + FAN
###############################################################

output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    id: fancontrol
    name: "${device_name} Fan"
    speed_count: 100   # <-- correct 0–100% speed!
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan Turned On!"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan Turned Off!"


###############################################################
# SCRIPTS
###############################################################

# 120-second shutdown timer (non-blocking)
script:
  - id: shutdown_fans
    mode: restart
    then:
      - logger.log: "Heating closed. Waiting 120 seconds for shutdown..."
      - delay: 120s
      - fan.turn_off: fancontrol
      - globals.set:
          id: heating_off
          value: 'true'
      - logger.log: "Fans OFF after timeout."

  # Main control logic script
  - id: control_fans
    mode: restart
    then:
      - lambda: |-
          float hs = id(heating_setting).state;
          ESP_LOGD("fan_logic", "Heating Setting: %.2f", hs);
          ESP_LOGD("fan_logic", "T1: %.2f  T2: %.2f", id(temp_1).state, id(temp_2).state);

          if (hs < 1.0f) {
            ESP_LOGD("fan_logic", "Heating OFF → Start shutdown timer.");
            id(shutdown_fans).execute();
            return;
          }

      # Heating 1–10 → 15% fixed speed
      - if:
          condition:
            lambda: 'return id(heating_setting).state >= 1 && id(heating_setting).state <= 10;'
          then:
            - logger.log: "Heating LOW → 15% fixed speed"
            - fan.turn_on:
                id: fancontrol
                speed: 15
            - globals.set:
                id: heating_off
                value: 'false'
            - return:

      # Heating >10 → Cooling mode
      - lambda: |-
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;
          float diff = fabs(t1 - t2);
          float fs = fmaxf(0.0f, fminf(100.0f, (20.0f - diff) * 5.0f));
          id(fanspeed) = fs;
          ESP_LOGD("fan_logic", "Cooling mode → Fan speed: %.2f", fs);

      - fan.turn_on:
          id: fancontrol
          speed: !lambda 'return id(fanspeed);'

      - globals.set:
          id: heating_off
          value: 'false'
