 ######################################################
#
# Main DBE configuration.
# Two Dallas temperature sensors calculate the difference between the incoming
# and outcoming water temperature. The aim is to have 20 degrees is a difference
# (But this will never be reached). The smaller the difference, the faster the fans go.
#
# There is a required sensor outside this config:
# sensor:
#  - platform: homeassistant
#    name: '${device_name} Heating Setting'
#    id: heating_setting
#    entity_id: sensor.living_room_heating
#
# This sensor indicates how 'open' the temperature valve is (I use Tado). When the valve
# is open (!= 0), the fans spin up. 120 seconds after the valve closes, all fans come to a full stop. 
# The boolean 'heating_off' is used to monitor this
#
####################################################################

######################################################
# Main DBE configuration – Clean & Fixed
######################################################

globals:
  - id: fanspeed
    type: float
    restore_value: no
    initial_value: '1'

  - id: heating_off
    type: bool
    initial_value: 'true'

  - id: mode_case
    type: int
    restore_value: no
    initial_value: '0'

logger:
  level: DEBUG

one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

######################################################
# SENSORS
######################################################

sensor:
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan
    on_value:
      then:
        - script.execute: control_fans

  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

######################################################
# SWITCH
######################################################

switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true

######################################################
# PWM + FAN
######################################################

output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    id: fancontrol
    output: pwm_output
    name: "${device_name} Fan"
    speed_count: 100
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan Turned On!"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan Turned Off!"

######################################################
# SCRIPTS
######################################################

script:
  # --- 120-second non-blocking shutdown ---
  - id: shutdown_fans
    mode: restart
    then:
      - logger.log: "Heating closed → waiting 120 seconds..."
      - delay: 120s
      - fan.turn_off: fancontrol
      - globals.set:
          id: heating_off
          value: 'true'
      - logger.log: "Fans OFF after delay."

  # --- Main fan logic ---
  - id: control_fans
    mode: restart
    then:
      - lambda: |-
          float hs = id(heating_setting).state;
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;

          ESP_LOGD("fan_logic", "Heating Setting=%.2f  T1=%.2f  T2=%.2f", hs, t1, t2);

          // Determine mode_case
          if (hs < 1.0f) {
            id(mode_case) = 0;   // Heating off
          } else if (hs <= 10.0f) {
            id(mode_case) = 1;   // Low heating
          } else {
            id(mode_case) = 2;   // Cooling / dynamic mode
          }

      # CASE 0 — Heating off
      - if:
          condition:
            lambda: 'return id(mode_case) == 0;'
          then:
            - logger.log: "Heating OFF → starting shutdown timer"
            - script.execute: shutdown_fans

      # CASE 1 — Low heat (15% speed)
      - if:
          condition:
            lambda: 'return id(mode_case) == 1;'
          then:
            - logger.log: "Heating LOW → fixed 15% speed"
            - globals.set:
                id: heating_off
                value: 'false'
            - fan.turn_on:
                id: fancontrol
                speed: 15

      # CASE 2 — Cooling mode (dynamic speed)
      - if:
          condition:
            lambda: 'return id(mode_case) == 2;'
          then:
            - lambda: |-
                float heating = id(heating_setting).state;

                // Safety: do not run if heating off
                if (heating < 1.0f) {
                  id(fanspeed) = 0;
                  return;
                }

                float deltaT = fabs(id(temp_1).state - id(temp_2).state);
                float target_delta = 20.0f;

                // Small ΔT → higher base speed
                float speed_base = fmaxf(0.0f, fminf(100.0f, (target_delta - deltaT) / target_delta * 100.0f));

                // Scale by heating level
                if (heating > 100) heating = 100.0f;
                float final_speed = speed_base * (heating / 100.0f);

                // Minimum airflow if heating > 1%
                if (heating > 1 && final_speed < 10) final_speed = 10;

                id(fanspeed) = final_speed;

                ESP_LOGD("fan_logic","ΔT=%.2f Heating=%.2f SpeedBase=%.2f Final=%.2f",
                  deltaT, heating, speed_base, final_speed);

            - if:
                condition:
                  lambda: 'return id(fanspeed) > 0;'
                then:
                  - globals.set:
                      id: heating_off
                      value: 'false'
                  - fan.turn_on:
                      id: fancontrol
                      speed: !lambda 'return id(fanspeed);'
                else:
                  - fan.turn_off: fancontrol
                  - globals.set:
                      id: heating_off
                      value: 'true'
