######################################################
# ESPHome: Interval-based fan control with HARD OFF
# - AUTO / MANUAL mode (Home Assistant)
# - Exponential fan curve based on ΔT
# - HARD OFF via relay when speed = 0
# - Interval control every 5 seconds
######################################################

globals:
  - id: fanspeed
    type: float
    restore_value: false
    initial_value: '0'

logger:
  level: DEBUG

######################################################
# OneWire bus
######################################################
one_wire:
  - platform: gpio
    pin: D1
    id: dallas_1

######################################################
# Sensors
######################################################
sensor:
  - platform: dallas_temp
    address: '${dallas_1_ID}'
    name: '${device_name} Dallas 1'
    id: temp_1
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan

  - platform: dallas_temp
    address: '${dallas_2_ID}'
    name: '${device_name} Dallas 2'
    id: temp_2
    update_interval: 30s
    accuracy_decimals: 1
    filters:
      - filter_out: nan

  - platform: pulse_counter
    pin: D5
    name: '${device_name} Fan RPM'
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5

######################################################
# Physical power relay (HARD OFF)
######################################################
switch:
  - platform: gpio
    pin: D0
    id: powerswitch
    internal: true
    restore_mode: ALWAYS_OFF

######################################################
# PWM output + Fan
######################################################
output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 1000 Hz
    max_power: 90%
    id: pwm_output

fan:
  - platform: speed
    id: fancontrol
    name: "${device_name} Fan"
    internal: true
    output: pwm_output
    speed_count: 100
    on_turn_on:
      - switch.turn_on: powerswitch
      - logger.log: "Fan turned ON"
    on_turn_off:
      - switch.turn_off: powerswitch
      - logger.log: "Fan turned OFF"

######################################################
# Home Assistant controls
######################################################
select:
  - platform: template
    name: "${device_name} Fan Mode"
    id: fan_mode
    optimistic: true
    options:
      - AUTO
      - MANUAL
    initial_option: AUTO

number:
  - platform: template
    name: "${device_name} Manual Fan Speed"
    id: manual_fanspeed
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    restore_value: true

######################################################
# Interval trigger
######################################################
interval:
  - interval: 5s
    then:
      - script.execute: control_fans

######################################################
# Fan control logic
######################################################
script:
  - id: control_fans
    mode: restart
    then:
      - lambda: |-
          // ==============================
          // MANUAL MODE
          // ==============================
          if (id(fan_mode).current_option() == "MANUAL") {
            id(fanspeed) = id(manual_fanspeed).state;
            return;
          }

          // ==============================
          // AUTOMATIC MODE
          // ==============================
          float t1 = id(temp_1).state;
          float t2 = id(temp_2).state;

          if (!isfinite(t1) || !isfinite(t2)) {
            id(fanspeed) = 0;
            return;
          }

          float deltaT = fabsf(t1 - t2);

          // --- HARD OFF hysteresis ---
          const float off_threshold = 1.5f;
          const float on_threshold  = 2.5f;

          static bool fan_was_on = false;

          if (!fan_was_on && deltaT < on_threshold) {
            id(fanspeed) = 0;
          } else if (fan_was_on && deltaT < off_threshold) {
            id(fanspeed) = 0;
          } else {
            // --- Exponential fan curve ---
            const float dt_min = 2.0f;
            const float dt_max = 20.0f;
            const float speed_min = 10.0f;
            const float speed_max = 80.0f;
            const float exponent = 2.5f;

            float x = (deltaT - dt_min) / (dt_max - dt_min);
            x = fmaxf(0.0f, fminf(1.0f, x));

            float curve = powf(x, exponent);
            id(fanspeed) = speed_min + curve * (speed_max - speed_min);
          }

          fan_was_on = id(fanspeed) > 0;

      # ==============================
      # APPLY FAN STATE
      # ==============================
      - if:
          condition:
            lambda: 'return id(fanspeed) > 0;'
          then:
            - fan.turn_on:
                id: fancontrol
                speed: !lambda 'return id(fanspeed);'
          else:
            - fan.turn_off: fancontrol

      # ==============================
      # LOGGING
      # ==============================
      - logger.log:
          format: "Mode=%s ΔT=%.2f Fanspeed=%.1f"
          args:
            - 'id(fan_mode).current_option().c_str()'
            - 'fabs(id(temp_1).state - id(temp_2).state)'
            - 'id(fanspeed)'
