# Read by the ESPHome Fleet add-on. Do not remove.
# esphome-fleet:
#   schedule: 0 10 * * 1
#   schedule_enabled: false
#   schedule_tz: Europe/Amsterdam
#   schedule_last_run: '2026-04-28T08:00:00.862688+00:00'

substitutions:
  device_name: display
  friendly_name: display
  device_description: lvgl display

esphome:
  name: '${device_name}'
  friendly_name: '${friendly_name}'
  comment: '${device_description}'
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kpsAzWAiBQmEW0IdGoduMdhKiQjFV7YIPrYXjXFTD1I="
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus
       
#Enable web server      
web_server:
  port: 80

globals:
  - id: climate_setpoint_value
    type: float
    restore_value: no
    initial_value: '21.0'

packages:
  Generic_config:
    url: https://github.com/BarBaar44/ESPHome
    files: [generic/wifi.yml, generic/generic_sensors.yml, LVGL/display.yml, LVGL/displayconfig.yml, LVGL/lvglconfig.yml, LVGL/lvglsensors.yml]
    refresh: 1min
