ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: True

bluetooth_proxy:
  active: true

button:
  - platform: restart
    name: '${device_name} restart'
    id: "restart_button"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      inverted: true
    name: "Restart Button"
    on_press: 
      then:
        - switch.turn_on: restart_switch

switch:
  - platform: restart
    name: '${device_name}  Restart'
    internal: True
    id: restart_switch

status_led:
  pin: GPIO32

output:
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: power_led
  - platform: gpio
    pin: GPIO12
    inverted: true
    id: ha_led
