# Read by the Fleet for ESPHome add-on. Do not remove.
# esphome-fleet:
#   schedule: 0 10 */7 * *
#   schedule_enabled: true
#   schedule_tz: Europe/Amsterdam
#   schedule_last_run: '2026-08-22T08:00:00.883318+00:00'

substitutions:
  device_name: dberoomgijs
  device_description: "DBE Room Gijs"
  dallas_1_ID: "0xd50000007c31fd28"
  dallas_2_ID: "0x590000007c286b28"
  WIFI_passwd: !secret wifi_password
  fallback_passwd: !secret wifi_bck
  friendly_name: "DBE Room Gijs"
  device_key: !secret dberoomgijs_key
  area: "Room Gijs"

esphome:
  name: dbe-room-gijs
  friendly_name: '${device_description}'

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

packages:
  Generic_config:
    url: https://github.com/BarBaar44/ESPHome
    files: [generic/wifi.yml, generic/generic_sensors.yml, DBE/DBEmain.yml]
    refresh: 1min