# Read by the Fleet for ESPHome add-on. Do not remove.
# esphome-fleet:
#   schedule: 0 10 */7 * *
#   schedule_enabled: true
#   schedule_tz: Europe/Amsterdam
#   schedule_last_run: '2026-08-22T08:00:01.191233+00:00'

substitutions:
  device_name: shelly-plug-tt
  device_description: "Shelly Plug Turbo Trainer"
  channel_1: "Turbo Trainer"
  WIFI_passwd: !secret wifi_password
  fallback_passwd: !secret wifi_bck
  device_key: !secret shelly-plug-tt_key
  friendly_name: "Shelly Plug Turbo Trainer"
  area: "Attic"

  # Higher value gives lower watt readout
  current_res: "0.000943"
  # Lower value gives lower voltage readout
  voltage_div: "2066"
  # measure a relatively strong load and enter values measured by the device vs the values your reference measurement provided here
  power_cal_meas: "1710.0"
  power_cal_real: "1685.0"

  max_current: "10"
  max_power: "2400"
  max_temp: "70.0"

packages:
  Generic_config:
    url: https://github.com/BarBaar44/ESPHome
    files: [generic/generic_sensors.yml, generic/wifi.yml, shelly/plug_s.yml]
    refresh: 1min