# Read by the Fleet for ESPHome add-on. Do not remove.
# esphome-fleet:
#   schedule: 0 10 */7 * *
#   schedule_enabled: true
#   schedule_tz: Europe/Amsterdam
#   schedule_last_run: '2026-09-01T08:00:01.146128+00:00'

substitutions:
  device_name: sonoff-tim
  device_description: Nachtlamp Tim
  channel_1: sonoff-tim
  WIFI_passwd: !secret wifi_password
  fallback_passwd: !secret wifi_bck
  device_key: !secret sonoff-tim_key
  friendly_name: "Nachtlamp Tim"
  area: "Room Tim"

packages:
  Generic_config:
    url: https://github.com/BarBaar44/ESPHome
    files: [generic/generic_sensors.yml, generic/wifi.yml, sonoff/basic.yml]
    refresh: 1min