# distributed-esphome:
#   schedule: 0 10 * * 2
#   schedule_enabled: true
#   schedule_tz: Europe/Amsterdam
#   schedule_last_run: '2026-04-22T08:00:00.036859+00:00'

substitutions:
  device_name: "bedsenst"
  device_description: Bed Sensor Test
  WIFI_passwd: !secret wifi_password
  fallback_passwd: "!paniek!"
  friendly_name: "Bed Sensor Test"

esphome:
  name: '${device_name}'
  friendly_name: '${friendly_name}'
  comment: '${device_description}'

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "wErKrg7W54PG8u2dNf3yjr8vukkrdNjqrXl8qq1Jrn0="

web_server:
  port: 80

packages:
  Generic_config:
    url: https://github.com/BarBaar44/ESPHome
    files: [generic/wifi.yml, generic/generic_sensors.yml]
    refresh: 1min

sensor:
  - platform: adc
    pin: A0
    name: "Master Bed Sensor"
    id: "master_bed_sensor"
    icon: mdi:bed
    update_interval: 0.5s
    filters:
      - multiply: 3.3
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - or:
          - throttle: 180s
          - delta: 0.02
    on_value: 
      then:
        - logger.log: "updating"

number:
  - platform: template
    name: Master Bed Trigger Level
    id: trigger_level
    optimistic: true
    restore_value: true
    min_value: 0
    max_value: 3.5
    step: 0.05
    icon: mdi:arrow-collapse-down
    unit_of_measurement: V 